package POJO;
// Generated May 25, 2019 11:25:52 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Author generated by hbm2java
 */
public class Author  implements java.io.Serializable {


     private Integer AId;
     private String AName;

    public Author() {
    }

    public Author(Integer AId, String AName) {
        this.AId = AId;
        this.AName = AName;
    }

    public Author(String AName) {
        this.AName = AName;
    }
   
    public Integer getAId() {
        return this.AId;
    }
    
    public void setAId(Integer AId) {
        this.AId = AId;
    }
    public String getAName() {
        return this.AName;
    }
    
    public void setAName(String AName) {
        this.AName = AName;
    }

    @Override
    public String toString() {
        return "Author{" + "AId=" + AId + ", AName=" + AName + '}';
    }




}


