package POJO;
// Generated May 25, 2019 11:25:52 AM by Hibernate Tools 4.3.1



/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private Integer bookId;
     private Author author;
     private String title;
     private float price;

    public Book() {
    }

    public Book(Integer bookId) {
        this.bookId = bookId;
    }

    public Book(Author author, String title, float price) {
       this.author = author;
       this.title = title;
       this.price = price;
    }

    public Book(Integer bookId, Author author, String title, float price) {
        this.bookId = bookId;
        this.author = author;
        this.title = title;
        this.price = price;
    }
   
    
    
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
    public Author getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Author author) {
        this.author = author;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }

//    @Override
//    public String toString() {
//        return "Book{" + "bookId=" + bookId + ", author=" + author + ", title=" + title + ", price=" + price + '}';
//    }

}


